bzm_website:
    resource: "@BZMWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

bzm_user:
    resource: "@BZMUserBundle/Controller"
    type:     annotation

bzm_core:
    resource: "@BZMCoreBundle/Controller"
    type:     annotation

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin